[2024-08-12T08:46:33.120+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.store_user scheduled__2024-08-11T00:00:00+00:00 [queued]>
[2024-08-12T08:46:33.129+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.store_user scheduled__2024-08-11T00:00:00+00:00 [queued]>
[2024-08-12T08:46:33.129+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-08-12T08:46:33.130+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-08-12T08:46:33.130+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-08-12T08:46:33.140+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): store_user> on 2024-08-11 00:00:00+00:00
[2024-08-12T08:46:33.145+0000] {standard_task_runner.py:55} INFO - Started process 14348 to run task
[2024-08-12T08:46:33.150+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'store_user', 'scheduled__2024-08-11T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpuboag5g2']
[2024-08-12T08:46:33.153+0000] {standard_task_runner.py:83} INFO - Job 29: Subtask store_user
[2024-08-12T08:46:33.222+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.store_user scheduled__2024-08-11T00:00:00+00:00 [running]> on host 7b166f9b76f0
[2024-08-12T08:46:33.288+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2024-08-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-08-11T00:00:00+00:00
[2024-08-12T08:46:33.290+0000] {postgres.py:129} INFO - Running copy expert: COPY users FROM stdin WITH DELIMITER as ',', filename: /tmp/processed_user.csv
[2024-08-12T08:46:33.305+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2024-08-12T08:46:33.315+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/user_processing.py", line 32, in _store_user
    filename='/tmp/processed_user.csv'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 137, in copy_expert
    cur.copy_expert(sql, file)
psycopg2.errors.BadCopyFileFormat: extra data after last expected column
CONTEXT:  COPY users, line 1: "Alieke,Straver,Netherlands,angrypanda158,blonds,alieke.straver@example.com"

[2024-08-12T08:46:33.329+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=user_processing, task_id=store_user, execution_date=20240811T000000, start_date=20240812T084633, end_date=20240812T084633
[2024-08-12T08:46:33.339+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 29 for task store_user (extra data after last expected column
CONTEXT:  COPY users, line 1: "Alieke,Straver,Netherlands,angrypanda158,blonds,alieke.straver@example.com"
; 14348)
[2024-08-12T08:46:33.362+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-08-12T08:46:33.382+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
