[2024-08-12T16:40:03.416+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.store_user scheduled__2024-08-11T00:00:00+00:00 [queued]>
[2024-08-12T16:40:03.426+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.store_user scheduled__2024-08-11T00:00:00+00:00 [queued]>
[2024-08-12T16:40:03.427+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-08-12T16:40:03.427+0000] {taskinstance.py:1363} INFO - Starting attempt 5 of 5
[2024-08-12T16:40:03.428+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-08-12T16:40:03.440+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): store_user> on 2024-08-11 00:00:00+00:00
[2024-08-12T16:40:03.446+0000] {standard_task_runner.py:55} INFO - Started process 19870 to run task
[2024-08-12T16:40:03.450+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'store_user', 'scheduled__2024-08-11T00:00:00+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpj1io7lkb']
[2024-08-12T16:40:03.453+0000] {standard_task_runner.py:83} INFO - Job 51: Subtask store_user
[2024-08-12T16:40:03.540+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.store_user scheduled__2024-08-11T00:00:00+00:00 [running]> on host 7b166f9b76f0
[2024-08-12T16:40:03.614+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2024-08-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-08-11T00:00:00+00:00
[2024-08-12T16:40:03.616+0000] {postgres.py:129} INFO - Running copy expert: COPY users FROM stdin WITH DELIMITER as ',', filename: /tmp/processed_user.csv
[2024-08-12T16:40:03.628+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2024-08-12T16:40:03.637+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/user_processing.py", line 18, in _store_user
    filename='/tmp/processed_user.csv'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 137, in copy_expert
    cur.copy_expert(sql, file)
psycopg2.errors.BadCopyFileFormat: extra data after last expected column
CONTEXT:  COPY users, line 1: "Manuela,Menard,Switzerland,silverduck973,russell,manuela.menard@example.com"

[2024-08-12T16:40:03.650+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=user_processing, task_id=store_user, execution_date=20240811T000000, start_date=20240812T164003, end_date=20240812T164003
[2024-08-12T16:40:03.660+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 51 for task store_user (extra data after last expected column
CONTEXT:  COPY users, line 1: "Manuela,Menard,Switzerland,silverduck973,russell,manuela.menard@example.com"
; 19870)
[2024-08-12T16:40:03.702+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-08-12T16:40:03.725+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
